const ProfileActionTypes = {
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCT_SUCCESS: " FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAIL: "FETCH_PRODUCT_FAIL",

  FETCH_PROFILE_START: "FETCH_PROFILE_START",
  FETCH_PROFILE_SUCCESS: " FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_FAIL: "FETCH_PROFILE_FAIL",
};

export default ProfileActionTypes;
