const ProductActionTypes = {
  ADD_NOFICATION_START: "ADD_NOFICATION_START",
  ADD_NOFICATION_SUCCESS: " ADD_NOFICATION_SUCCESS",
  ADD_NOFICATION_FAIL: "ADD_NOFICATION_FAIL",

  GET_NOFICATION_DETAIL_START: "GET_NOFICATION_DETAIL_START",
  GET_NOFICATION_DETAIL_SUCCESS: "GET_NOFICATION_DETAIL_SUCCESS",
  GET_NOFICATION_DETAIL_FAIL: "GET_NOFICATION_DETAIL_FAIL",

  UPDATE_NOFICATION_DETAIL_START: "UPDATE_NOFICATION_DETAIL_START",
  UPDATE_NOFICATION_DETAIL_SUCCESS: "UPDATE_NOFICATION_DETAIL_SUCCESS",
  UPDATE_NOFICATION_DETAIL_FAIL: "UPDATE_NOFICATION_DETAIL_FAIL",

  DELETE_NOFICATION_DETAIL_START: "DELETE_NOFICATION_DETAIL_START",
  DELETE_NOFICATION_DETAIL_SUCCESS: "DELETE_NOFICATION_DETAIL_SUCCESS",
  DELETE_NOFICATION_DETAIL_FAIL: "DELETE_NOFICATION_DETAIL_FAIL",

  GET_NOFICATIONS_START: "GET_NOFICATIONS_START",
  GET_NOFICATIONS_SUCCESS: "GET_NOFICATIONS_SUCCESS",
  GET_NOFICATIONS_FAIL: "GET_NOFICATIONS_FAIL",

  CLEAR_NOFICATION_DETAIL: "CLEAR_NOFICATION_DETAIL",
};

export default ProductActionTypes;
