const ProductActionTypes = {
  ADD_NOFICATION_START: "ADD_NOFICATION_START",
  ADD_NOFICATION_SUCCESS: " ADD_NOFICATION_SUCCESS",
  ADD_NOFICATION_FAIL: "ADD_NOFICATION_FAIL",
  GET_NOFICATION_DETAIL_START: "GET_NOFICATION_DETAIL_START",
  GET_NOFICATION_DETAIL_SUCCESS: "GET_NOFICATION_DETAIL_SUCCESS",
  GET_NOFICATION_DETAIL_FAIL: "GET_NOFICATION_DETAIL_FAIL",
  UPDATE_NOFICATION_DETAIL_START: "UPDATE_NOFICATION_DETAIL_START",
  UPDATE_NOFICATION_DETAIL_SUCCESS: "UPDATE_NOFICATION_DETAIL_SUCCESS",
  UPDATE_NOFICATION_DETAIL_FAIL: "UPDATE_NOFICATION_DETAIL_FAIL",
};

export default ProductActionTypes;
