const ProductActionTypes = {
  ADD_NOFICATION_START: "ADD_NOFICATION_START",
  ADD_NOFICATION_SUCCESS: " SEARCH_PRODUCTS_SUCCESS",
  ADD_NOFICATION_FAIL: "SEARCH_PRODUCTS_FAIL",
  GET_NOFICATION_DETAIL_START: "GET_PRODUCT_DETAIL_START",
  GET_NOFICATION_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  GET_NOFICATION_DETAIL_FAIL: "GET_PRODUCT_DETAIL_FAIL",
  CLEAR_NOFICATION_DETAIL: "CLEAR_PRODUCT_DETAIL",
};

export default ProductActionTypes;
