const ProductActionTypes = {
  SEARCH_PRODUCTS_START: "SEARCH_PRODUCTS_START",
  SEARCH_PRODUCTS_SUCCESS: " SEARCH_PRODUCTS_SUCCESS",
  SEARCH_PRODUCTS_FAIL: "SEARCH_PRODUCTS_FAIL",
  GET_PRODUCT_DETAIL_START: "GET_PRODUCT_DETAIL_START",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  GET_PRODUCT_DETAIL_FAIL: "GET_PRODUCT_DETAIL_FAIL",
  CLEAR_PRODUCT_DETAIL: "CLEAR_PRODUCT_DETAIL",
};

export default ProductActionTypes;
