const ProductActionTypes = {
  SEARCH_PRODUCTS_START: "SEARCH_PRODUCTS_START",
  SEARCH_PRODUCTS_SUCCESS: " SEARCH_PRODUCTS_SUCCESS",
  SEARCH_PRODUCTS_FAIL: "SEARCH_PRODUCTS_FAIL",
  SORT_PRODUCTS: "SORT_PRODUCTS",
};

export default ProductActionTypes;
